var appEN = {
    'GlobalSelections.ShowFields': 'Show fields',
    'GlobalSelections.FilterDimensions': 'Search dimensions',
    'GlobalSelections.FilterDimensionsAndFields': 'Search dimensions and fields',
    "equalizer.label.datos": 'Data',
    "equalizer.label.ordenar": 'Sorting',
    "equalizer.label.presentacion": 'Presentation',
    "equalizer.label.colores": 'Colors and legend',
    "equalizer.label.cabecerasyetiquetas": 'Headers and labels',
    "equalizer.label.cabecera": 'Headers ',
    "equalizer.label.superponeretiquetas": 'Overlay labels',
    "equalizer.label.etiquetashojas": 'Leaf labels',
    "equalizer.label.etiquetasvalores": 'Value labels',
    "equalizer.label.titulos": 'Titles',
    "equalizer.label.dimensiones": 'Dimensions',
    "equalizer.label.medidas": 'Measures',
    "equalizer.label.campos": 'Fields',
    "equalizer.label.ascendente": 'Ascending',
    "equalizer.label.descendente": 'Descending',
    "equalizer.label.valoresextremos": 'Include outliers',
    "equalizer.label.vertical": 'Vertical',
    "equalizer.label.horizontal": 'Horizontal',
    "equalizer.label.agrupado": 'Grouped',
    "equalizer.label.apilado": 'Stacked',
    "equalizer.label.valoresperdidos": 'Missing values',
    "equalizer.label.mostrarhuecos": 'Show as gaps',
    "equalizer.label.mostrarconexiones": 'Show as connections',
    "equalizer.label.mostrarceros": 'Show as zeros',
    "equalizer.label.mostrarpuntos": 'Show data points',
    "equalizer.label.tamanioburbuja": 'Bubble size',
    "equalizer.label.reolucioncompresion": 'Compression resolution',
    "equalizer.label.puntosfluctuacion": 'Jitter points',
    "equalizer.label.activado": 'On',
    "equalizer.label.desactivado": 'Off',
    "equalizer.label.personalizado": 'Custom',
    "equalizer.label.colorunico": 'Single color',
    "equalizer.label.porDimension": 'By dimension',
    "equalizer.label.porMedida": 'By measure',
    "equalizer.label.multicolor": 'Multicolored',
    "equalizer.label.esquemacolor": 'Color scheme',
    "equalizer.label.mostrarleyenda": 'Show legend',
    "equalizer.label.mostrarleyendaTitulo": 'Show legend title',
    "equalizer.label.mostrartitulo": 'Show titles',
    "equalizer.label.mostraretiqueta": 'Show label',
    "equalizer.label.titulo": 'Title',
    "equalizer.label.subtitulo": 'Subtitle',
    "equalizer.label.piepagina": 'Footnote',
    "equalizer.label.posicionleyenda": 'Legend position',
    "equalizer.label.posicion": 'Position',
    "equalizer.label.automatico": 'Auto',
    "equalizer.label.derecha": 'Right',
    "equalizer.label.final": 'Bottom',
    "equalizer.label.izquierda": 'Left',
    "equalizer.label.principio": 'Top',
    "equalizer.label.etiquetavalores": 'Value labels',
    "equalizer.label.capas": 'Layers',
    "equalizer.label.configuracionmapa": 'Map settings',
    "equalizer.label.idiomamapa": 'Map language',
    "equalizer.label.capa.puntos": 'Point layer',
    "equalizer.label.capa.grafico": 'Chart layer',
    "equalizer.label.capa.lineas": 'Line layer',
    "equalizer.label.capa.densidad": 'Density layer',
    "equalizer.label.capa.area": 'Area layer',
    "equalizer.label.capa.fondo": 'Background layer',
    "equalizer.label.mapabase": 'Base map',
    "equalizer.label.prederminado": 'Default',
    "equalizer.label.palido": 'Pale',
    "equalizer.label.satelite": 'Satellite',
    "equalizer.label.ninguna": 'None',
    "equalizer.label.todos": 'All',
    "equalizer.label.cuota": 'Share',
    "equalizer.label.valores": 'Values',
    "equalizer.label.ingles": 'English',
    "equalizer.label.local": 'Local',
    "equalizer.label.zoomauto": 'Auto-zoom',
    "equalizer.label.mostrarcapa": 'Show layer',
    "equalizer.label.tamanioburbuja": 'Bubble size',
    "equalizer.label.rangoburbuja": 'Bubble size range',
    "equalizer.label.rangotriangulo": 'Triangle size range',
    "equalizer.label.rangocuadrado": 'Square size range',
    "equalizer.label.rangopentagono": 'Pentagon size range',
    "equalizer.label.rangohexagono": 'Hexagon size range',
    "equalizer.label.rangotarta": 'Pie chart size',
    "equalizer.label.rangolinea": 'Line width',
    "equalizer.label.radioinfluencia": 'Influence radiux',
    "equalizer.label.alto": 'Height',
    "equalizer.label.ancho": 'Width',
    "equalizer.label.navegacion": 'Navigation',
    "equalizer.label.etiquetas": 'Labels',
    "equalizer.label.linea": 'Line',
    "equalizer.label.area": 'Area',
    "equalizer.label.escalalogaritmica": 'Logarithmic scale',
    "equalizer.label.tarta": 'Pie',
    "equalizer.label.donut": 'Donut',
    "equalizer.label.colorespersistentes": 'Persistent colors',
    "equalizer.label.expandirtodo": 'Expand all',
    "equalizer.label.contraertodo": 'Collapse all',
    "equalizer.label.tablatotales": 'Totals',
    "equalizer.label.desplazamiento": 'Scrolling',
    "equalizer.label.inmovilizarColumna": 'Freeze first column',
    "equalizer.label.desHorizontal": 'Horizontal scrolling',
    "equalizer.label.ajustesTexto": 'Multiline text wrapping',
    "equalizer.label.textoCabecera": 'Wrap text in headers',
    "equalizer.label.textoCelda": 'Wrap text in cells',
    "equalizer.label.filtros": "Filters",
    "equalizer.label.stylesline": "Line styles",
    "equalizer.btn.guardar": 'Save',
    "equalizer.btn.aplicar": 'Apply',
    "equalizer.btn.cancelar": 'Cancel',
    "equalizer.btn.cerrar": 'Close',
    "equalizer.btn.descartar": 'Discard',
    "equalizer.title.mover": 'Move',
    "equalizer.title.ascendente": 'Ascending',
    "equalizer.title.descendente": 'Descending',
    "equalizer.title.vertical": 'Vertical',
    "equalizer.title.horizontal": 'Horizontal',
    "equalizer.modal.atencion": 'Attention',
    "equalizer.modal.aviso": 'Changes have not been saved.',
    "equalizer.modal.avisoClose": 'Discard changes.',
    "equalizer.modal.cambios": 'Apply the changes?',
    "equalizer.modal.cambiosexplicacion": 'All changes will be applied to the properties of the object.',
    "equalizer.modal.errormensaje": 'Selection has created an inconsistency.',
    "equalizer.language.spaniol": 'Spanish',
    "equalizer.language.ingles": 'English',
    "equalizer.language.frances": 'French',
    "contextmenu.label.downloadas": 'Download as',
    "contextmenu.label.expand": "Expand/Collapse",
    "contextmenu.label.menuexploracion": 'Open exploration menu',
    "contextmenu.label.closemenuexploracion": 'Close exploration menu',
    "contextmenu.label.fullsize": 'Full screen',
    "contextmenu.label.normalsize": 'Exit full screen',
    "contextmenu.label.softPatches": 'Return initial state',
    "contextmenu.label.copyToClipboard": 'Copy cell value',
    "contextmenu.label.verdatos": 'View data',
    "contextmenu.label.vergrafico": 'View chart',
    "contextmenu.label.vergraficodatos": 'View chart / data',
    "contextmenu.label.compartir": 'Share',
    "contextmenu.label.exportimagen": 'Export as an image',
    "contextmenu.label.exportpdf": 'Export to PDF',
    "contextmenu.label.exportdatos": 'Export data',
    "contextmenu.label.expandirtodo": 'Expand all',
    "contextmenu.label.contraertodo": 'Collapse all',
    "contextmenu.label.volver": 'Back',
    "contextmenu.label.showToggleVisualizations": 'Show Toggle Visualizations',
    "contextmenu.label.compararObjetos": 'Comparative',
    "contextmenu.label.ayuda": 'Help',
    "compare.label.estadoInicial": "Return graph to its initial state",
    "compareobject.btn.messageopen": 'Select what you want to compare with..',
    "compareobject.btn.sameobject": 'Same graphic',
    "compareobject.btn.listobject": 'Choose from list',
    "compare.btn.newstate": 'New state',
    "compare.btn.listastaters": 'States list',
    "compare.btn.exportpdf": 'Export to PDF',
    "compare.tooltips.close": 'Close the window deleting the created states',
    "compareobject.btn.hideFilterSection": "Hide filters",
    "compareobject.btn.showFilterSection": "Show filters",
    "compare.label.filtersMensaje": "Apply selections from the fields below to explore the associations in your data.",
    "compare.tooltips.createsatate": 'Create a new state.',
    "compare.tooltips.openliststates": 'Open list of created states',
    "compare.tooltips.sameobject": 'Choose the initial graph to compare it with itself',
    "compare.tooltips.listobject": 'Choose a chart from the list to compare it',
    "compare.modal.headermodal": 'Create new state',
    "compare.modal.labeltitle": 'State title',
    "compare.modal.mensajepdf": 'Downloading PDF',
    "compare.acciones.KOState": "You must enter the name of the state",
    "compare.acciones.CrearState": "The state has been created",
    "compare.acciones.DeleteState": "The state has been removed",
    "compare.acciones.EliminarState": "Status has been removed",
    "compare.acciones.Stateexiste": "There is already a state with this name. Give the state another name.",
    "compare.acciones.fullsize": "Full size",
    "compare.acciones.normalsize": "Full size exit",
    "compare.acciones.vistaColumna": "Column view",
    "compare.acciones.vistaRow": "Row View",
    "compare.pdf.Objeto_1": "Generating main object image",
    "compare.pdf.Objeto_2": "Generating secondary object image",
    "compare.pdf.selecciones_1": "Generating main object selections",
    "compare.pdf.selecciones_2": "Generating child object selections",
    "compare.pdf.imgCoorporativa": "Obtaining corporate image",
    "compare.pdf.title": "Graphics comparison",
    "compare.pdf.objetoPrincipal": "Main graph",
    "compare.pdf.objetoSecundario": "Selected graph",
    "compare.tooltips.estadoInicial": "Return graph to its initial state",
    'compare.tooltips.reloadObject': "Reload the chart",
    "compare.tooltips.exportimagen": "Export as an image",
    "compare.tooltips.exportdatos": "Export data",
    "compare.tooltips.addFilter": "Add selection to chart",
    "compare.pdf.selecciones": "Selections",
    "compare.pdf.addtitle": "PDF Title",
    "compare.pdf.askForTitle": "Please enter a title for your report.",
    "compare.pdf.txtCaracter": "characters",
    "compare.object.error": "Sorry, an unexpected error occurred. Please try again later. If the issue persists, feel free to contact our support team for help. Sorry for the disturbances.",
    "views.login.seleccionar": "Select language",
    "views.acciones.acciones": "Actions",
    "views.acciones.marcadores": "Bookmark",
    "views.acciones.ayuda": "Help",
    "views.acciones.configuracion": "Configuration",
    "views.acciones.aniadirmarcadores": "Add Bookmark",
    "views.acciones.mas": "More",
    "views.acciones.filtros": "Filters",
    "views.acciones.bloquear": "Lock",
    "views.acciones.desbloquear": "Unlock",
    "views.acciones.limpiarselecciones": "Clear selections",
    "views.acciones.crearmarcadores": "Create new bookmark",
    "views.acciones.editarmarcadores": "Edit bookmark",
    "views.acciones.marcadorepredeterminado": "Mark as default",
    "views.acciones.aplicarmarcadores": "Apply bookmark",
    "views.acciones.vervisualizacion": "See visualization",
    "views.acciones.seleccionartodos": "Select all",
    "views.acciones.eliminar": "Delete",
    "views.acciones.eliminarseleccionados": "Delete selected",
    "views.acciones.OKbookmark": "The bookmark has been created",
    "views.acciones.KObookmark": "You must enter the name of the bookmark",
    "views.acciones.OKbookmarkUpdate": "The bookmark has been updated",
    "views.acciones.CrearBookmark": "The bookmark has been created",
    "views.acciones.EliminarBookmark": "The marker has been removed",
    "views.acciones.Bookmarkexiste": "A bookmark with this title already exists. Assign another title to the bookmark.",
    "views.acciones.seeliminaraBookmar": "The bookmark will be deleted.",
    "views.acciones.OKpublishBookmark": "The bookmark has been published",
    "views.acciones.OKunPublishBookmark": "The bookmark has been unpublished",
    "views.acciones.KOpublishBookmark": "The bookmark could not be published",
    "views.acciones.KOunpublishBookmark": "The bookmark could not be unpublished",
    "views.acciones.filtrosSeleccionados": "Selected Filters",
    "views.acciones.anclaritem": "Pin this item to the list",
    "views.acciones.desanclaritem": "Unpin this item from the list",
    "views.acciones.publicarmarcador": "Make bookmark public",
    "views.acciones.despublicarmarcador": "Make bookmark private",
    "views.acciones.publicarvisualizacion": "Make the visualization public.",
    "views.acciones.despublicarvisualizacion": "Make the visualization private",
    "views.acciones.mensajebookmarkpublico": `<h3>This marker will be made public.</h3><p>Other users in the organization will be able to see this bookmark.</p><p>This action can be reversed.</p>`,
    "views.acciones.mensajebookmarkprivado": `<h3>This bookmark will be made private.</h3><p>Only you will be able to see this marker.</p><p>This action can be reversed.</p>`,
    "views.acciones.mensajevisualizacionpublico": `<h3>This visualization will be made public.</h3><p>Other users in the organization will be able to see this visualization.</p><p>This action can be reversed.</p>`,
    "views.acciones.mensajevisualizacionprivado": `<h3>This visualization will be made private.</h3><p>Only you will be able to see this visualization.</p><p>This action can be reversed.</p>`,
    'views.modal.usuario': "User",
    'views.modal.appname': "Section",
    'views.modal.crearmarcador': "Create bookmark",
    'views.modal.editarmarcador': "Edit Bookmark",
    "views.modal.crearmarcadortitulo": "Title",
    "views.modal.crearmarcadordescripcion": "Description",
    "views.modal.fechaCreacion": "Creation date",
    "views.modal.fechaModificacion": "Modification date",
    "views.modal.selecciones": "Selections",
    "views.modal.opcional": "(Optional)",
    "views.modal.hoja": 'Save sheet location',
    "views.modal.guardar": "Save",
    "views.modal.cerrar": "Close",
    "views.modal.exportar": "Export",
    "views.modal.crear": "Create",
    "views.modal.continuar": "Continue",
    "views.modal.aceptar": "Ok",
    "views.modal.atencion": "Attention",
    "views.modal.accionnoback": "This action can not be undone. Do you wish to continue?",
    "views.modal.pdf": "PDF configurations",
    "views.modal.tamaniopapel": "Paper size",
    "views.modal.carta": "Letter",
    "views.modal.orientacion": "Orientation",
    "views.modal.vertical": "Vertical",
    "views.modal.apaisado": "Landscape",
    "views.modal.opcionesaspecto": "Aspect ratio options",
    "views.modal.actual": "Keep current size",
    "views.modal.ajustar": "Fit to page",
    "views.modal.invalidparams": "<h3>We have detected an error in the comparison module.</h3><br /> We are going to reload the page to solve it. <br />Try the comparison again.",
    "views.label.selecciones": "Selections",
    "views.label.filtros": "Filters",
    "views.label.glosario": "Glossary",
    "views.label.alertas": "Alerts",
    "views.label.modo": "Mode",
    "views.label.modeview": "Day / Night mode",
    "views.label.preferencias": "Preferences",
    "views.label.nofiltros": "No filters selected",
    "views.label.noBookmark": "No bookmarks yet",
    "views.label.noAlerts": "There are no alerts yet",
    "views.label.cerrar": "Close",
    "views.label.logout": "Sign off",
    "views.label.logoutconfirm": "Are you sure to log out",
    "views.label.DimensionesMedidas": "Dimensions and Measurements",
    "views.label.buscar": "Search for",
    "views.label.openapp": "Opening app...",
    "views.label.esperar": "Please wait...",
    "views.label.loadobject" : "Load object  ",
    "views.label.of" : " of ",
    "views.label.descripcion": "Description",
    "views.label.LastReloadTime": "Last update",
    "template.label.template": "Template skin customizer",
    "views.label.fechaCreacion": "Creation Date",
    "template.label.themes": "Custom themes",
    "template.label.sidebarimages": "Sidebar Background Imagen",
    "template.label.sidebarcolor": "Sidebar Background Cover Color",
    "template.label.headercolor": "Header Background  Color",
    "template.label.backgroundimage": "Background image",
    "template.label.menucolor": "Menu color",
    "template.label.saveconfig": "Save settings",
    "template.label.cliente": "Client",
    "template.label.proyecto": "Project",
    "template.label.enlazarhoja": "Link to sheet",
    "template.label.seleccionarhoja": "Select a sheet",
    'view.menu.GestionFiltros': 'Filter Management',
    'dialog.configuracioneimagen': 'Image settings',
    'dialog.actual': 'Current',
    'dialog.personalizado': 'Custom',
    'views.notificaciones': 'Notifications',
    "views.idioma.es": "Spanish",
    "views.idioma.en": "English",
    "views.idioma.fr": "French",
    "label.filtros.todo": "Select all",
    "label.filtros.posibles": "Select possible",
    "label.filtros.alternativos": "Select alternative",
    "label.filtros.excluidos": "Select excluded",
    "label.filtros.borrar": "Clear selection",
    "label.filtros.bloquear": "Click to lock",
    "label.filtros.desbloquear": "Click to unlock",
    "label.filtros.retroceder": "Step back",
    "label.filtros.avanzar": "Step forward",
    "label.filtros.limpiar": "Clear all selections",
    "message.anclarElemento": "Pin this item to the list",
    "message.desanclarElemento": "Unpin this item from the list",
    "label.Bookmarks.StartBookmark": "Default",
    "label.Bookmarks.StartBookmarkUser": "Default by user",
    "label.Bookmarks.StartBookmarkHint": "This flag will be applied when you open the app, including the sheet and selection state.",
    "label.Bookmarks.BookmarkActive": "Active bookmark",
    "label.Bookmarks.NoBookmarkActive": "There is no Bookmark selected",
    "label.Bookmarks.GuardarByUser" : "Save bookmark as default",
    "message.Bookmarks.BookmarkByUserExist": `<h4>A predefined Bookmark already exists.</h4> <br> Do you want to update?`,
    "Tooltip.Bookmarks.StartBookmark": "This bookmark will be applied when opening the app.",
    "Favorites.title.label": "Favorites",
    "Favorites.create.label": "Created at",
    "Favorites.create.date": "Added",
    "Favorites.label.addFavorites": "Add to favorites",
    "Favorites.label.deltetFavorites": "Remove from favorites",
    "Favorites.label.askForDelete": "Are you sure you want to remove the favorite item from your list?",
    "Favorites.AlternarFullSizw.label": "Toggle Fullsize",
    "Favorites.GoPage.label": "Go to the page where the object is located",
    "Favorites.Delete.label": "Remove from Favorite",
    "Favorites.Delete.Modal": "Are you sure you want to remove this object as a favourite?",
    "Favorites.Modo.Objeto": "Object view mode",
    "Favorites.Modo.Lista": "List view mode",
    "Favorites.Wellcome": `<h3>Welcome to the screen of your favorites.</h3><p>You don't have any favorites yet, but you can add your favorite visualizations to this place by clicking <i class="ri-more-2-fill"></i> on the button located on each object, report or chart by selecting the option “Add to Favorites” </p><p>At any time you can remove favorites from this list by clicking the star icon.</p>`,
    "Favorites.itemaction.loadapp": "Upload app items",
    "Favorites.itemaction.fullsize": "Toggle full size",
    "Favorites.itemaction.gotopage": "Go to the page where the object is located",
    "Favorites.itemaction.deletefavorite": "Remove from favorites",
    "Favorites.alert.addToFavorites": "Item added to favorites",
    "Favorites.alert.deleteToFavorites": "Item removed from favorites",
    "Favorites.alert.errorToFavorites": "Error adding to favorites",
    "order.menu.nombreHoja": "Sheet Name",
    "order.menu.publicado": "Published",
    "order.menu.aprovado": "Approved",
    "order.menu.fechacreacion": "Creation date",
    "order.menu.fechapublicacion": "Publish time",
    "order.menu.fechamodificacion": "Modified Date",
    "order.menu.propietario": "Owner",
    "sheets.modal.title": "Custom Sheet Information",
    "sheets.modal.SI": "YES",
    "sheets.modal.NO": "NO",
    "sheets.menu.sheet": "Custom sheets",
    "sheets.openapp": "Open app",
    "blockloading.openapp": "Opening the app...",
    "blockloading.cargandoobjetos": "Loading Objects ",
    "blockloading.de": " of ",
    "label.colorPalette": "Color Palette",
    "label.colorOptions": "Color options",
    "label.loadvideos": "Looking for help videos....",
    "label.novideos": "There are currently no help videos uploaded.",
    "label.visualizaciones": "Views",
    "placeholder.buscarvisualizaciones": "Search visualizations...",
    "visualizaciones.buscando": "Searching for custom views",
    "visualizaciones.noresultados": "You don't have any custom visualization yet.",

    "treepermissions.titles.roles": "Roles",
    "treepermissions.titles.perfiles": "Profiles",
    "treepermissions.titles.groups": "Groups",
    "treepermissions.titles.users": "Users",
    "treepermissions.titles.functionality": "Functionality",
    "treepermissions.titles.identification": "Identification",
    "treepermissions.titles.rulesapplied": "Rules applied",
    "treepermissions.actions.selectall": "select all",
    "treepermissions.actions.newuser": "new user",
    "treepermissions.actions.newgroup": "new group",
    "treepermissions.actions.newrole": "new role",
    "treepermissions.actions.newprofile": "new profile",
    "treepermissions.placeholder.search": "search...",
    "treepermissions.buttons.new": "New",
    "treepermissions.buttons.new.role": "Role",
    "treepermissions.buttons.new.profile": "Profile",
    "treepermissions.buttons.new.group": "Group",
    "treepermissions.buttons.new.user": "User",
    "treepermissions.buttons.assign": "Assign",
    "treepermissions.buttons.delete": "Delete",
    "treepermissions.buttons.rules": "Rules",
    "treepermissions.buttons.save": "Save",
    "treepermissions.buttons.add": "Add",
    "treepermissions.buttons.accept": "Accept",
    "treepermissions.buttons.cancel": "Cancel",
    "treepermissions.buttons.close": "Close",
    "treepermissions.buttons.replace": "Replace",
    "treepermissions.buttons.edit": "Edit",
    "treepermissions.buttons.expandall": "Expand All",
    "treepermissions.buttons.collapseall": "Collapse All",
    "treepermissions.rules.empty": "There are no rules to show",
    "treepermissions.legend.allowed": "Allowed",
    "treepermissions.legend.blocked": "Blocked",
    "treepermissions.legend.indeterminate": "Indeterminate",
    "treepermissions.legend.blank": "Blank",
    "treepermissions.modals.userform.user": "User",
    "treepermissions.modals.userform.firstname": "First Name",
    "treepermissions.modals.userform.lastname": "Last Name",
    "treepermissions.modals.userform.domain": "Domain",
    "treepermissions.modals.userform.gender": "Gender",
    "treepermissions.modals.userform.email": "e-Mail",
    "treepermissions.modals.userform.address": "Address",
    "treepermissions.modals.userform.phone": "Phone",
    "treepermissions.modals.userform.role": "Role",
    "treepermissions.modals.userform.birthday": "Birthday",
    "treepermissions.modals.delete.title": "Do you want to delete the selections?",
    "treepermissions.modals.assign.title": "Assign Groups",
    "treepermissions.modals.assign.body": "Do you want to add or replace the selected groups?",
    "treepermissions.modals.assign.role.title": "Assign Role",
    "treepermissions.modals.assign.role.body": "Do you want to replace the selected role?",
    "treepermissions.modals.assign.profile.title": "Assign Profile",
    "treepermissions.modals.assign.profile.body": "Do you want to replace the selected profile?",
    "treepermissions.modals.delete.rule.title": "Delete rule",
    "treepermissions.modals.delete.rule.body": "Do you want to delete the rule '{{rule}}'?",

    "treepermissions.modals.save.label": "Save options",
    "treepermissions.modals.save.title": "What do you want to save?",
    "treepermissions.modals.save.section1": "Options",
    "treepermissions.modals.save.section1.opt1": "Add permissions to users",
    "treepermissions.modals.save.section1.opt1small": "Permissions will be added to users without deleting the ones already created.",
    "treepermissions.modals.save.section1.opt2": "Replace selected permissions",
    "treepermissions.modals.save.section1.opt2small": "Old permissions will be erased and replaced by selected ones.",
    "treepermissions.modals.save.section1.opt3": "Create a permission rule",
    "treepermissions.modals.save.section1.opt3small": "A rule will be created that applies the permissions to the selection. It is necessary to have selected a role or group.",
    "treepermissions.modals.save.section2": "Selections",
    "treepermissions.modals.save.section2.opt1": "Only apply to selected users",
    "treepermissions.modals.save.section2.opt2": "Apply to selected and related users",
    "treepermissions.modals.save.section3": "Rule Name",
    "treepermissions.modals.save.section3.replace": "The rule already exists, do you want to replace it?",
    "treepermissions.modals.save.section3.required": "A rule name is required",
    "treepermissions.modals.save.section3.placeholder": "Write a rule name...",

    "treepermissions.toast.permissionsload": 'Permissions loaded successfully!',
    "treepermissions.toast.roleupdate": "Role successfully updated",
    "treepermissions.toast.rolecreate": "Role successfully created",
    "treepermissions.toast.profileupdate": "Profile successfully updated",
    "treepermissions.toast.profilecreate": "Profile successfully created",
    "treepermissions.toast.groupupdate": "Group successfully updated",
    "treepermissions.toast.groupcreate": "Group successfully created",
    "treepermissions.toast.roledelete": "Role '{{role}}' successfully removed",
    "treepermissions.toast.profiledelete": "Profile '{{role}}' successfully removed",
    "treepermissions.toast.groupdelete": "Group '{{group}}' successfully removed",
    "treepermissions.toast.userdelete": "User '{{user}}' successfully removed",
    "treepermissions.toast.deleteselerror": "It is necessary to select at least one user, one role or one group",
    "treepermissions.toast.deleteselerrorperfil": "It is necessary to select at least one user, one profile or one group",
    "treepermissions.toast.assignselerror01": "It is necessary to select at least one user and one role or group",
    "treepermissions.toast.assignselerror01perfil": "It is necessary to select at least one user and one profile or group",
    "treepermissions.toast.assignselerror02": "Only one role per user is allowed",
    "treepermissions.toast.assignselerror02perfil": "Only one profile per user is allowed",
    "treepermissions.toast.assignselsuccess01": "Group and roles have been added successfully",
    "treepermissions.toast.assignselsuccess01perfil": "Group and profiles have been added successfully",
    "treepermissions.toast.assignselsuccess02": "Group and roles have been successfully replaced",
    "treepermissions.toast.assignselsuccess02perfil": "Group and profiles have been successfully replaced",
    "treepermissions.toast.assignselsuccess03": "Rol have been successfully replaced",
    "treepermissions.toast.assignselsuccess03perfil": "Profile have been successfully replaced",
    "treepermissions.toast.savedialogsuccesscreated": "User successfully created",
    "treepermissions.toast.savedialogsuccessupdated": "User successfully updated",
    "treepermissions.toast.savedialogerror": "At least one functionality needs to be selected",
    "treepermissions.toast.rulecreate": "Rule '{{rule}}' created succesfully",
    "treepermissions.toast.permissionscreate": "Permissions created succesfully",
    "treepermissions.toast.ruledelete": "Rule '{{rule}}' successfully removed",
    "treepermissions.toast.sequelizeerrorforeignkey": "Error, the record is being referenced in another table",
    //Bookmark
    'views.bookmark.modolista': `List mode view`,
    'views.bookmark.mododetalle': `Detail mode view`,
    'views.bookmark.mybookmark': 'My Bookmarks',
    //EMBED
    'views.embed.mensaje': 'We recommend that you embed objects in internal web pages only. The visualization will be updated when the app is updated.',
    'views.embed.SI': 'Yes',
    'views.embed.NO': 'No',
    'views.embed.allowInteraction': 'Allow interaction',
    'views.embed.enableContextMenu': 'Enable context menu',
    'alerting.dial.alertas': `Alerts`,
    'alerting.label.todas': `All alerts`,
    'alerting.label.fecha': `Date/Hour`,
    'alerting.label.nombre': `Name`,
    'alerting.label.mensaje': `Message`,
    'alerting.label.fechaleida': `Date/Hour read`,
    'alerting.label.leertodas': `Mark all as read`,
    'alerting.label.leeralerta': `Mark as read`,
    'alerting.label.noalertassinleer': `No unread alerts`,
    'alerting.label.vertodas': `See all`,
    'alerting.label.confirmacion': `Confirmation`,
    'alerting.label.confirdelete': 'Delete the alert definition and its alert?',
    'alerting.label.cancel': 'Cancel',
    'alerting.label.configuracion': `Alert settings`,
    'alerting.label.configuracion.general': `General`,
    'alerting.label.configuracion.alerta': `Alert`,
    'alerting.label.configuracion.mensaje': `Message`,
    'alerting.label.configuracion.tipo': `Alert type`,
    'alerting.label.configuracion.app': `Application`,
    'alerting.label.configuracion.hoja': `Mashup Sheet`,
    'alerting.label.configuracion.medidaCondiciones': `Measure and Conditions`,
    'alerting.label.configuracion.medida': `Measure`,
    'alerting.label.configuracion.valores': `Fixed value / Percentage`,
    'alerting.label.configuracion.tipoCondicion': `Condition type`,
    'alerting.label.configuracion.maximo': `Maximum`,
    'alerting.label.configuracion.minimo': `Minimum`,
    'alerting.label.configuracion.guardar': `Save`,
    'alerting.label.configuracion.eliminar': `Remove`,
    'alerting.label.configuracion.cerrar': `Close`,
    'alerting.label.configuracion.master.error': `Error`,
    'alerting.label.configuracion.master.advertencia': `Warning`,
    'alerting.label.configuracion.master.informacion': `Información`,
    'alerting.label.configuracion.master.exito': `Success`,
    'alerting.label.configuracion.master.data': `About the data`,
    'alerting.label.configuracion.master.system': `Of system`,
    'alerting.label.configuracion.master.valorFijo': `Fixed value`,
    'alerting.label.configuracion.master.valorPorcentaje': `Porcentaje`,
    'alerting.label.configuracion.master.minmax': `Minimum-Maximum`,
    'alerting.label.configuracion.master.min': `Minimum`,
    'alerting.label.configuracion.master.max': `Maximum`,
    'alerting.toast.mensajeCreacionAlerta': `Alert has been created`,
    'alerting.toast.mensajeEliminacionAlerta': `The definition and its alert have been removed`,
    'alerting.toast.mensajeCreacionDefinicion': `Alert definition created`,
    'alerting.toast.mensajeEliminacionDefinicion': `Definition has been removed`,
    'alerting.toast.mensajeActualizacionDefinicion': `Alert definition updated`,
    'grid.header.tituloGrafico': `Graphic title`,
    'grid.header.tipoGrafico': `Graphic type`,
    'grid.header.seccionGrafico': `Section`,
    'grid.header.idGrafico': `Graphic ID`,
    'grid.header.fechaCreación': `Added`,
    'grid.header.rutaLocalizacion': `Route location`,
    'grid.header.acciones': `Actions`,
    'grid.header.fecha-creacion': `Creation date`,
    'grid.header.fecha-modificacion': `Modification date`,
    'grid.header.tipo-grafico': `Graphic type`,
    'grid.header.user': `User`,
    'grid.header.seccion': `Section`,
    //AYUDA OBJETOS
    'help.label.descripcionTab': 'Description',
    'help.label.detalleTab': 'Detail',
    'help.label.layoutTab': 'Layout',
    'help.btn.editar': 'Edit',
    'help.txt.detalleTab': '<h2>Dimensions:</h2><p>Dimensions are attributes that organize and categorize data. They represent the variables used to split, group, or segment data in a Qlik Sense application.</p><p>Dimensions allow you to perform detailed analysis and break down data into different categories.</p><p>In visualizations such as tables and charts, dimensions are placed on axes, rows, or columns to organize the information.</p><p>When selecting or interacting with a dimension, the associated measures are dynamically recalculated, allowing interactive exploration of the data.</p><h2>Measurements:</h2><p>Measures represent numerical values that are analyzed and aggregated in a Qlik Sense application. They are quantitative metrics that provide information about performance, sales, quantities, etc.</p><p>Measurements are used to perform calculations and aggregations on dimension data.</p><p>In graphs and tables, measurements are used on Y-axes or as values to represent the magnitude of the data.</p><p>Measurements are essential to understand the magnitude and trend of the data, allowing comparative analysis and obtaining quantitative insights.</p><h2>Relationship between Dimensions and Measurements:</h2><p>Dimensions and measures work together to provide a complete understanding of the data. Dimensions organize and group data, while measures perform calculations on that grouped data.</p><p>When you make selections on dimensions, the measures automatically adjust to reflect the impact of those selections, allowing for interactive and dynamic exploration of the data.</p>',
    'help.txt.selectIdioma': 'Select a language to save changes',
    //PRESENTACIÓN
    'presentacion.tooltips.init': 'Presentation mode'
};
var custom = {
    'view.wellcome.title': `Welcome to the Qlik portfolio of Jherlan Choque Calle`,
    'view.wellcome.bigText': `Explore my data without limits.`,
    'view.wellcome.smallText': `Comprehensive analysis of business, infrastructure, and official statistical data.`,
    'view.menu.ventas': 'Sales',
    'view.menu.compras': "Purchases",
    'view.menu.financiero': 'Financial',
    'view.menu.logistica': 'Logistics',
    'view.menu.personal': 'Staff',
    'view.menu.crm': 'CRM',
    'view.menu.produccion': 'Production',
    'view.menu.nps': 'NPS',
    'view.wellcomeMenu.favoritos': `Favorites`,
    'label.filtro.calendario': 'Calendar',
    'label.filtro.anios': 'Years',
}
var translationsEN = $.extend(true, appEN, custom);