var appES = {
    'GlobalSelections.ShowFields': 'Mostrar campos',
    'GlobalSelections.FilterDimensions': 'Buscar dimensiones',
    'GlobalSelections.FilterDimensionsAndFields': 'Buscar dimensiones y campos',
    "equalizer.label.datos": 'Datos',
    "equalizer.label.ordenar": 'Ordenar',
    "equalizer.label.presentacion": 'Presentación',
    "equalizer.label.colores": 'Colores y Leyendas',
    "equalizer.label.cabecerasyetiquetas": 'Cabeceras y etiquetas',
    "equalizer.label.cabecera": 'Cabeceras',
    "equalizer.label.superponeretiquetas": 'Superponer etiquetas',
    "equalizer.label.etiquetashojas": 'Etiquetas de hojas',
    "equalizer.label.etiquetasvalores": 'Etiquetas de valores',
    "equalizer.label.titulos": 'Títulos',
    "equalizer.label.dimensiones": 'Dimensiones',
    "equalizer.label.medidas": 'Medidas',
    "equalizer.label.campos": 'Campos',
    "equalizer.label.ascendente": 'Ascendente',
    "equalizer.label.descendente": 'Descendente',
    "equalizer.label.valoresextremos": 'Incluir valores extremos',
    "equalizer.label.vertical": 'Vertical',
    "equalizer.label.horizontal": 'Horizontal',
    "equalizer.label.agrupado": 'Agrupado',
    "equalizer.label.apilado": 'Apilado',
    "equalizer.label.valoresperdidos": 'Valores perdidos',
    "equalizer.label.mostrarhuecos": 'Mostrar como huecos',
    "equalizer.label.mostrarconexiones": 'Mostrar como conexiones',
    "equalizer.label.mostrarceros": 'Mostrar como ceros',
    "equalizer.label.mostrarpuntos": 'Mostrar puntos de datos',
    "equalizer.label.tamanioburbuja": 'Tamaño de burbuja',
    "equalizer.label.reolucioncompresion": 'Resolución de compresión',
    "equalizer.label.puntosfluctuacion": 'Puntos de fluctuación',
    "equalizer.label.activado": 'Activado',
    "equalizer.label.desactivado": 'Desactivado',
    "equalizer.label.personalizado": 'Personalizado',
    "equalizer.label.colorunico": 'Color único',
    "equalizer.label.porDimension": 'Por dimensión',
    "equalizer.label.porMedida": 'Por medida',
    "equalizer.label.multicolor": 'Multicolor',
    "equalizer.label.esquemacolor": 'Esquema de color',
    "equalizer.label.mostrarleyenda": 'Mostrar leyenda',
    "equalizer.label.mostrarleyendaTitulo": 'Mostrar título de leyenda',
    "equalizer.label.mostrartitulo": 'Mostrar títulos',
    "equalizer.label.mostraretiqueta": 'Mostrar etiqueta',
    "equalizer.label.titulo": 'Título',
    "equalizer.label.subtitulo": 'Subtítulo',
    "equalizer.label.piepagina": 'Nota a pie de página',
    "equalizer.label.posicionleyenda": 'Posición de leyenda',
    "equalizer.label.posicion": 'Posición',
    "equalizer.label.automatico": 'Automático',
    "equalizer.label.derecha": 'Derecha',
    "equalizer.label.final": 'Final',
    "equalizer.label.izquierda": 'Izquierda',
    "equalizer.label.principio": 'Principio',
    "equalizer.label.etiquetavalores": 'Etiquetas de valores',
    "equalizer.label.capas": 'Capas',
    "equalizer.label.configuracionmapa": 'Configuraciones de mapa',
    "equalizer.label.idiomamapa": 'Idioma del mapa',
    "equalizer.label.capa.puntos": 'Capa de puntos',
    "equalizer.label.capa.grafico": 'Capa de gráfico',
    "equalizer.label.capa.lineas": 'Capa de lineas',
    "equalizer.label.capa.densidad": 'Capa de densidad',
    "equalizer.label.capa.area": 'Capa de área',
    "equalizer.label.capa.fondo": 'Capa de fondo',
    "equalizer.label.mapabase": 'Mapa base',
    "equalizer.label.prederminado": 'Predeterminado',
    "equalizer.label.palido": 'Pálido',
    "equalizer.label.satelite": 'Satélite',
    "equalizer.label.ninguna": 'Ninguna',
    "equalizer.label.todos": 'Todos',
    "equalizer.label.cuota": 'Cuota',
    "equalizer.label.valores": 'Valores',
    "equalizer.label.ingles": 'Inglés',
    "equalizer.label.local": 'Local',
    "equalizer.label.zoomauto": 'Zoom automático',
    "equalizer.label.mostrarcapa": 'Mostrar capa',
    "equalizer.label.tamanioburbuja": 'Tamaño de burbuja',
    "equalizer.label.rangoburbuja": 'Rango de tamaño de la burbuja',
    "equalizer.label.rangotriangulo": 'Tamaño de triángulo',
    "equalizer.label.rangocuadrado": 'Tamaño de cuadrado',
    "equalizer.label.rangopentagono": 'Tamaño de pentágono',
    "equalizer.label.rangohexagono": 'Tamaño de hexágono',
    "equalizer.label.rangotarta": 'Tamaño del gráfico de tarta',
    "equalizer.label.rangolinea": 'Ancho de línea',
    "equalizer.label.radioinfluencia": 'Radio de influencia',
    "equalizer.label.alto": 'Alto',
    "equalizer.label.ancho": 'Ancho',
    "equalizer.label.navegacion": 'Navegación',
    "equalizer.label.etiquetas": 'Etiquetas',
    "equalizer.label.linea": 'Linea',
    "equalizer.label.area": 'Área',
    "equalizer.label.escalalogaritmica": 'Escala logarítmica',
    "equalizer.label.tarta": 'Tarta',
    "equalizer.label.donut": 'Donut',
    "equalizer.label.colorespersistentes": 'Colores persistentes',
    "equalizer.label.expandirtodo": 'Expandir todo',
    "equalizer.label.contraertodo": 'Contraer todo',
    "equalizer.label.tablatotales": 'Totales',
    "equalizer.label.desplazamiento": 'Desplazamiento',
    "equalizer.label.inmovilizarColumna": 'Inmovilizar primera columna',
    "equalizer.label.desHorizontal": 'Desplazamiento horizontal',
    "equalizer.label.ajustesTexto": 'Ajustes de texto multilinea',
    "equalizer.label.textoCabecera": 'Ajustar texto de cabecera',
    "equalizer.label.textoCelda": 'Ajustar texto de celda',
    "equalizer.label.filtros": "Filtros",
    "equalizer.label.stylesline" : "Estilos de línea",
    "equalizer.btn.guardar": 'Guardar',
    "equalizer.btn.aplicar": 'Aplicar',
    "equalizer.btn.cancelar": 'Cancelar',
    "equalizer.btn.cerrar": 'Cerrar',
    "equalizer.btn.descartar": 'Descartar',
    "equalizer.title.mover": 'Mover',
    "equalizer.title.ascendente": 'Ascendente',
    "equalizer.title.descendente": 'Descendente',
    "equalizer.title.vertical": 'Vertical',
    "equalizer.title.horizontal": 'Horizontal',
    "equalizer.modal.atencion": 'Atención',
    "equalizer.modal.aviso": 'No se han guardado los cambios.',
    "equalizer.modal.avisoClose": 'Descartar cambios.',
    "equalizer.modal.cambios": '¿Aplicar los cambios?',
    "equalizer.modal.cambiosexplicacion": 'Todos los cambios se aplicarán a las propiedades del objeto.',
    "equalizer.modal.errormensaje": 'La selección ha creado una inconsistencia.',
    "equalizer.language.spaniol": 'Español',
    "equalizer.language.ingles": 'Inglés',
    "equalizer.language.frances": 'Francés',
    "contextmenu.label.downloadas": 'Descargar como',
    "contextmenu.label.expand": "Expandir/Contraer",
    "contextmenu.label.menuexploracion": 'Abrir menú de exploración',
    "contextmenu.label.closemenuexploracion": 'Cerrar menú de exploración',
    "contextmenu.label.fullsize": 'Pantalla completa',
    "contextmenu.label.normalsize": 'Salir del modo de pantalla completa',
    "contextmenu.label.softPatches": 'Volver estado inicial',
    "contextmenu.label.copyToClipboard": 'Copiar valor de celda',
    "contextmenu.label.verdatos": 'Ver datos',
    "contextmenu.label.vergrafico": 'Ver gráfico',
    "contextmenu.label.vergraficodatos": 'Ver gráfico / datos',
    "contextmenu.label.compartir": 'Compartir',
    "contextmenu.label.exportimagen": 'Exportar como imagen',
    "contextmenu.label.exportpdf": 'Exportar a PDF',
    "contextmenu.label.exportdatos": 'Exportar datos',
    "contextmenu.label.expandirtodo": 'Expandir todo',
    "contextmenu.label.contraertodo": 'Contraer todo',
    "contextmenu.label.volver": 'Volver',
    "contextmenu.label.showToggleVisualizations": 'Mostrar Alternar Visualizaciones', 
    "contextmenu.label.compararObjetos": 'Comparativa', 
    "contextmenu.label.ayuda": 'Ayuda',
    "compare.label.estadoInicial" : "Devolver gráfico a su estado inicial",
    "compareobject.btn.messageopen": 'Selecciona con que quieres hacer la comparación..',
    "compareobject.btn.sameobject": 'Mismo gráfico', 
    "compareobject.btn.listobject": 'Elegir de la lista',  
    "compare.btn.newstate": 'Nuevo estado',
    "compare.btn.listastaters": 'Lista estados',
    "compare.btn.exportpdf": 'Exportar a PDF',
    "compare.tooltips.close": 'Cerrar la ventana eliminando los estados creados',
    "compareobject.btn.hideFilterSection": "Ocultar filtros",
    "compareobject.btn.showFilterSection": "Mostrar filtros",
    "compare.label.filtersMensaje" : "Aplique selecciones desde los campos a continuación para explorar las asociaciones en sus datos.",
    "compare.tooltips.createsatate": 'Crear un nuevo estado.',
    "compare.tooltips.openliststates": 'Abrir lista de los estados creados',
    "compare.tooltips.sameobject": 'Elegir el gráfico inicial para compararlo consigo mismo',
    "compare.tooltips.listobject": 'Elegir un gráfico de la lista para compararlo',
    "compare.modal.headermodal": 'Crear nuevo estado',
    "compare.modal.labeltitle": 'Título estado',
    "compare.modal.mensajepdf": 'Descargando PDF',
    "compare.acciones.KOState": "Debe introducir el nombre del estado",
    "compare.acciones.CrearState": "Se ha creado el estado",
    "compare.acciones.DeleteState": "Se ha eliminado el estado",
    "compare.acciones.EliminarState": "Se ha eliminado el estado",
    "compare.acciones.Stateexiste": "Ya existe un estado con este nombre. Asigne otro nombre al estado.",
    "compare.acciones.fullsize": "Pantalla completa", 
    "compare.acciones.normalsize": "Salir pantalla completa",
    "compare.acciones.vistaColumna" : "Vista columna",
    "compare.acciones.vistaRow" : "Vista fila", 
    "compare.pdf.Objeto_1" : "Generando imagen objeto principal", 
    "compare.pdf.Objeto_2" : "Generando imagen objeto secundario", 
    "compare.pdf.selecciones_1" : "Generando selecciones objeto principal",
    "compare.pdf.selecciones_2" : "Generando selecciones objeto secundario",
    "compare.pdf.imgCoorporativa": "Obteniendo imágen corporativa",
    "compare.pdf.title": "Comparativa de gráficos",
    "compare.pdf.objetoPrincipal": "Gráfica principal",
    "compare.pdf.objetoSecundario": "Gráfica seleccionada",
    "compare.tooltips.estadoInicial" : "Devolver gráfico a su estado inicial",
    'compare.tooltips.reloadObject' : "Recargar el gráfico",
    "compare.tooltips.exportimagen" : "Exportar como imagen",
    "compare.tooltips.exportdatos" : "Exportar datos",
    "compare.tooltips.addFilter" : "Añadir selección al gráfico",
    "compare.pdf.selecciones": "Selecciones",
    "compare.pdf.addtitle": "Título PDF",
    "compare.pdf.askForTitle" : "Por favor, ingrese un título para su informe.",
    "compare.pdf.txtCaracter" : "caracteres",
    "compare.object.error": "Lo sentimos, se ha producido un error inesperado. Por favor, inténtalo de nuevo más tarde. Si el problema persiste, no dudes en ponerte en contacto con nuestro equipo de soporte para obtener ayuda. Disculpa las molestias.",
    "views.login.seleccionar": "Seleccionar Idioma",
    "views.acciones.acciones": "Acciones",
    "views.acciones.marcadores": "Marcadores", 
    "views.acciones.ayuda": "Ayuda",
    "views.acciones.configuracion": "Configuración",
    "views.acciones.aniadirmarcadores": "Añadir Marcador",
    "views.acciones.mas": "Más",
    "views.acciones.filtros": "Filtros",
    "views.acciones.bloquear": "Bloquear",
    "views.acciones.desbloquear": "Desbloquear",
    "views.acciones.limpiarselecciones": "Limpiar selecciones",
    "views.acciones.crearmarcadores": "Crear nuevo marcador",
    "views.acciones.editarmarcadores": "Editar marcador",
    "views.acciones.marcadorepredeterminado" : "Marcar como predeterminado", 
    "views.acciones.aplicarmarcadores": "Aplicar marcador",
    "views.acciones.vervisualizacion": "Ver visualización",
    "views.acciones.seleccionartodos": "Seleccionar todos",
    "views.acciones.eliminar": "Eliminar",
    "views.acciones.eliminarseleccionados": "Eliminar seleccionados",
    "views.acciones.OKbookmark": "Se ha creado el marcador",
    "views.acciones.KObookmark": "Debe introducir el nombre del marcador",
    "views.acciones.OKbookmarkUpdate": "El marcador se ha actualizado",
    "views.acciones.CrearBookmark": "Se ha creado el marcador",
    "views.acciones.EliminarBookmark": "Se ha eliminado el marcador",
    "views.acciones.Bookmarkexiste": "Ya existe un marcador con este título. Asigne otro título al marcador.",
    "views.acciones.seeliminaraBookmar": "Se eliminará el marcador.",
    "views.acciones.OKpublishBookmark": "El marcador ha sido publicado.",
    "views.acciones.OKunPublishBookmark": "El marcador ha sido despublicado.",
    "views.acciones.KOpublishBookmark": "No se pudo publicar el marcador.",
    "views.acciones.KOunpublishBookmark": "El marcador no se pudo despublicar",
    "views.acciones.filtrosSeleccionados": "Filtros Seleccionados",
    "views.acciones.anclaritem": "Anclar este elemento a la lista",
    "views.acciones.desanclaritem": "Desanclar este elemento de la lista",
    "views.acciones.publicarmarcador": "Hacer público el marcador",
    "views.acciones.despublicarmarcador": "Hacer privado el marcador",
    "views.acciones.publicarvisualizacion": "Hacer público la visualización",
    "views.acciones.despublicarvisualizacion": "Hacer privado la visualización",
    "views.acciones.mensajebookmarkpublico": `<h3>Este marcador se hará público</h3><p>El resto de usuarios de la organización podrán ver este marcador.</p><p>Esta acción puede revertirse.</p>`,
    "views.acciones.mensajebookmarkprivado": `<h3>Este marcador se hará privado</h3><p>Solo tu podrás ver este marcador.</p><p>Esta acción puede revertirse.</p>`,
    "views.acciones.mensajevisualizacionpublico": `<h3>Esta visualización se hará pública.</h3><p>Otros usuarios de la organización podrán ver esta visualización.</p><p>Esta acción se puede revertir.</p>`,
    "views.acciones.mensajevisualizacionprivado": `<h3>Esta visualización se hará privada.</h3><p>Sólo tú podrás ver esta visualización.</p><p>Esta acción se puede revertir.</p>`,
    'views.modal.usuario': "Usuario",
    'views.modal.appname': "Sección",
    'views.modal.crearmarcador': "Crear marcador",
    'views.modal.editarmarcador': "Editar marcador",
    "views.modal.crearmarcadortitulo": "Título",
    "views.modal.crearmarcadordescripcion": "Descripción",
    "views.modal.fechaCreacion": "Fecha creación",
    "views.modal.fechaModificacion": "Fecha modificación",
    "views.modal.selecciones": "Selecciones",
    "views.modal.opcional": "(Opcional)",
    "views.modal.hoja" : 'Guardar ubicación de hoja',
    "views.modal.guardar": "Guardar",
    "views.modal.cerrar": "Cerrar",
    "views.modal.exportar": "Exportar",
    "views.modal.crear": "Crear",
    "views.modal.continuar": "Continuar",
    "views.modal.aceptar": "Aceptar",
    "views.modal.atencion": "Atención",
    "views.modal.accionnoback": "Esta acción no se puede deshacer. Desea continuar?",
    "views.modal.pdf": "Configuraciones de PDF",
    "views.modal.tamaniopapel": "Tamaño de papel",
    "views.modal.carta": "Carta",
    "views.modal.orientacion": "Orientación",
    "views.modal.vertical": "Vertical",
    "views.modal.apaisado": "Apaisado",
    "views.modal.opcionesaspecto": "Opciones de ratio de aspecto",
    "views.modal.actual": "Mantener tamaño actual",
    "views.modal.ajustar": "Ajustar a la página",
    "views.modal.invalidparams" : "<h3>Hemos detectado un error en el módulo de comparación.</h3><br /> Vamos a recargar la página para solucionarlo. <br /> Intenta otra vez la comparación.",
    "views.label.selecciones": "Selecciones",
    "views.label.filtros": "Filtros",
    "views.label.glosario": "Glosario",
    "views.label.alertas": "Alertas",
    "views.label.modo": "Modo",
    "views.label.modeview" : "Modo Día/Noche",
    "views.label.preferencias" : "Preferencias",
    "views.label.nofiltros" : "No hay filtros seleccionados",
    "views.label.noBookmark" : "No hay marcadores aún",
    "views.label.noAlerts" : "No hay alertas aún",
    "views.label.cerrar": "Cerrar",
    "views.label.logout": "Cerrar sesión",
    "views.label.logoutconfirm": "¿Está seguro de cerrar la sesión?",
    "views.label.DimensionesMedidas": "Dimensiones y Medidas",
    "views.label.buscar": "Buscar",
    "views.label.openapp": "Abriendo aplicación...",
    "views.label.esperar": "Por favor espere...",
    "views.label.loadobject" : "Cargando Objetos  ",
    "views.label.of" : " de ",
    "views.label.descripcion": "Descripción",
    "views.label.LastReloadTime": "Última actualización",
    "template.label.template": "Personalizar plantilla",
    "views.label.fechaCreacion": "Fecha creación",
    "template.label.themes": "Temas personalizados",
    "template.label.sidebarimages": "Imagen de fondo de la barra lateral",
    "template.label.sidebarcolor": "Color de fondo de la barra lateral",
    "template.label.headercolor": "Color de fondo de la cabecera",
    "template.label.backgroundimage": "Imagen de fondo",
    "template.label.menucolor": "Color item menú",
    "template.label.saveconfig": "Guardar configuración",
    "template.label.cliente": "Cliente",
    "template.label.proyecto": "Proyecto",
    "template.label.enlazarhoja": "Enlazar a hoja",
    "template.label.seleccionarhoja": "Seleccione una hoja",
    'view.menu.GestionFiltros': 'Gestión de Filtros',
    'dialog.configuracioneimagen': 'Configuraciones de imagen',
    'dialog.actual': 'Actual',
    'dialog.personalizado': 'Personalizado',
    'views.notificaciones': 'Notificaciones',
    "views.idioma.es": "Español",
    "views.idioma.en": "Inglés",
    "views.idioma.fr": "Francés",
    "label.filtros.todo" : "Seleccionar todo",
    "label.filtros.posibles" : "Seleccionar posibles",
    "label.filtros.alternativos" : "Seleccionar alternativos",
    "label.filtros.excluidos" : "Seleccionar excluidos",
    "label.filtros.borrar" : "Borrar selección",
    "label.filtros.bloquear" : "Haga clic para bloquearla",
    "label.filtros.desbloquear" : "Haga clic para desbloquearla",
    "label.filtros.retroceder" : "Retroceder",
    "label.filtros.avanzar" : "Avanzar",
    "label.filtros.limpiar" : "Borrar todas las selecciones",
    "message.anclarElemento" : "Anclar este elemento a la lista",
    "message.desanclarElemento" : "Desanclar este elemento de la lista",
    "label.Bookmarks.StartBookmark": "Predeterminado",
    "label.Bookmarks.StartBookmarkUser": "Predeterminado por usuario",
    "label.Bookmarks.StartBookmarkHint": "Este marcador se aplicará al abrir la app, incluida la hoja y el estado de selección.",
    "label.Bookmarks.BookmarkActive": "Bookmark activo",
    "label.Bookmarks.NoBookmarkActive": "No hay ningun Bookmark seleccionado",
    "label.Bookmarks.GuardarByUser" :"Guardar marcador como predefino",
    "message.Bookmarks.BookmarkByUserExist": `<h4>Ya existe un Bookmark predefinido.</h4> <br> Quieres actualizar?`,
    "Tooltip.Bookmarks.StartBookmark": "Este marcador se aplicará al abrir la app.",
    "Favorites.title.label": "Favoritos",
    "Favorites.create.label": "Añadido en",
    "Favorites.create.date": "Añadido",
    "Favorites.label.addFavorites": "Agregar a los favoritos",
    "Favorites.label.deltetFavorites": "Eliminar de favoritos",
    "Favorites.label.askForDelete" : "¿Estás seguro de eliminar el objeto favorito de tu lista?",
    "Favorites.AlternarFullSizw.label": "Alternar tamaño completo",
    "Favorites.GoPage.label": "Ir a la página donde se encuentra el objeto",
    "Favorites.Delete.label": "Eliminar de Favoritos",
    "Favorites.Delete.Modal": "¿Estás seguro de eliminar este objeto como favorito?",
    "Favorites.Modo.Objeto" :"Modo vista Objeto",
    "Favorites.Modo.Lista" :"Modo vista Lista",
    "Favorites.Wellcome": `<h3>Bienvenido a la pantalla de tus favoritos.</h3><p>Aún no tiene ningún elemento favorito, pero puede agregar sus visualizaciones preferidas a este lugar haciendo clic <i class="ri-more-2-fill"></i> en el botón ubicado en cada objeto, informe o gráfico seleccionando la opción “Agregar a favoritos” </p><p>En cualquier momento puede eliminar favoritos de esta lista haciendo clic en el icono de estrella.</p>`,
    "Favorites.itemaction.loadapp": "Cargar elementos de aplicación",
    "Favorites.itemaction.fullsize": "Alternar tamaño completo",
    "Favorites.itemaction.gotopage": "Ir a la página donde se encuentra el objeto",
    "Favorites.itemaction.deletefavorite": "Eliminar de favoritos",
    "Favorites.alert.addToFavorites": "Elemento añadido a favoritos",
    "Favorites.alert.deleteToFavorites": "Elemento eliminado de favoritos",
    "Favorites.alert.errorToFavorites": "Error al añadir a favorito",
    "order.menu.nombreHoja": "Nombre de Hoja",
    "order.menu.publicado": "Publicado",
    "order.menu.aprovado": "Aprobado",
    "order.menu.fechacreacion": "Fecha de creación",
    "order.menu.fechapublicacion": "Hora de publicación",
    "order.menu.fechamodificacion": "Fecha de modificación",
    "order.menu.propietario": "Propietario",
    "sheets.modal.title": "Información Hoja Personalizada",
    "sheets.modal.SI": "SI",
    "sheets.modal.NO": "NO",
    "sheets.menu.sheet": "Hojas personalizadas",
    "sheets.openapp": "Abrir aplicación",
    "blockloading.openapp": "Abriendo la aplicación...",
    "blockloading.cargandoobjetos": "Cargando Objetos ",
    "blockloading.de": " de ",
    "label.colorPalette" : "Paleta de color",
    "label.colorOptions" : "Opciones de color",
    "label.loadvideos" : "Buscando videos de ayuda....",
    "label.novideos" : "Actualmente no hay videos de ayuda subidos.",
    "label.visualizaciones" : "Visualizaciones",
    "placeholder.buscarvisualizaciones": "Buscar visualizaciones...",
    "visualizaciones.buscando" : "Buscando vistas personalizadas",
    "visualizaciones.noresultados" : "Aún no tiene ninguna visualización personalizada.",
    
    "treepermissions.titles.roles": "Roles",
    "treepermissions.titles.perfiles": "Perfiles",
    "treepermissions.titles.groups": "Grupos",
    "treepermissions.titles.users": "Usuarios",
    "treepermissions.titles.functionality": "Opciones",
    "treepermissions.titles.identification": "Información personal",
    "treepermissions.titles.rulesapplied": "Reglas aplicadas",
    "treepermissions.actions.selectall": "seleccionar todos",
    "treepermissions.actions.newuser": "nuevo usuario",
    "treepermissions.actions.newgroup": "nuevo grupo",
    "treepermissions.actions.newrole": "nuevo rol",
    "treepermissions.actions.newprofile": "nuevo perfil",
    "treepermissions.placeholder.search": "buscar...",
    "treepermissions.buttons.new": "Nuevo",
    "treepermissions.buttons.new.role": "Rol",
    "treepermissions.buttons.new.profile": "Perfil",
    "treepermissions.buttons.new.group": "Grupo",
    "treepermissions.buttons.new.user": "Usuario",
    "treepermissions.buttons.assign": "Asignar",
    "treepermissions.buttons.delete": "Eliminar",
    "treepermissions.buttons.rules": "Reglas",
    "treepermissions.buttons.save": "Guardar",
    "treepermissions.buttons.add": "Añadir",
    "treepermissions.buttons.accept": "Aceptar",
    "treepermissions.buttons.cancel": "Cancelar",
    "treepermissions.buttons.close": "Cerrar",
    "treepermissions.buttons.replace": "Reemplazar",
    "treepermissions.buttons.edit": "Editar",
    "treepermissions.buttons.expandall": "Expandir todo",
    "treepermissions.buttons.collapseall": "Contraer todo",
    "treepermissions.rules.empty": "No hay reglas para mostrar",
    "treepermissions.legend.allowed": "Permitir",
    "treepermissions.legend.blocked": "Bloquear",
    "treepermissions.legend.indeterminate": "Sin determinar",
    "treepermissions.legend.blank": "Vacío",
    "treepermissions.modals.userform.user": "Usuario",
    "treepermissions.modals.userform.firstname": "Nombre",
    "treepermissions.modals.userform.lastname": "Apellidos",
    "treepermissions.modals.userform.domain": "Dominio",
    "treepermissions.modals.userform.gender": "Género",
    "treepermissions.modals.userform.email": "e-Mail",
    "treepermissions.modals.userform.address": "Dirección",
    "treepermissions.modals.userform.phone": "Teléfono",
    "treepermissions.modals.userform.role": "Rol",
    "treepermissions.modals.userform.birthday": "Cumpleaños",
    "treepermissions.modals.delete.title": "¿Quieres eliminar lo seleccionado?",
    "treepermissions.modals.assign.title": "Asignar grupos",
    "treepermissions.modals.assign.body": "¿Desea añadir o reemplazar los grupos seleccionados?",
    "treepermissions.modals.assign.role.title": "Asignar rol",
    "treepermissions.modals.assign.role.body": "¿Desea reemplazar el rol seleccionado?",
    "treepermissions.modals.assign.profile.title": "Asignar perfil",
    "treepermissions.modals.assign.profile.body": "¿Desea reemplazar el perfil seleccionado?",
    "treepermissions.modals.delete.rule.title": "Eliminar la regla",
    "treepermissions.modals.delete.rule.body": "¿Quieres eliminar la regla '{{rule}}'?",

    "treepermissions.modals.save.label": "Opciones de guardado",
    "treepermissions.modals.save.title": "¿Qué quieres guardar?",
    "treepermissions.modals.save.section1": "Opciones",
    "treepermissions.modals.save.section1.opt1": "Añadir los permisos a los usuarios",
    "treepermissions.modals.save.section1.opt1small": "Se añadirán los permisos a los usuarios sin eliminar los ya creados.",
    "treepermissions.modals.save.section1.opt2": "Reemplazar permisos seleccionados",
    "treepermissions.modals.save.section1.opt2small": "Los permisos antiguos serán borrados y reemplazados por los seleccionados.",
    "treepermissions.modals.save.section1.opt3": "Crear una regla",
    "treepermissions.modals.save.section1.opt3small": "Se creará una regla que aplique los permisos a la selección. Es necesario haber seleccionado un rol o un grupo.",
    "treepermissions.modals.save.section2": "Selecciones",
    "treepermissions.modals.save.section2.opt1": "Solo se aplica a usuarios seleccionados",
    "treepermissions.modals.save.section2.opt2": "Se aplica a usuarios seleccionados y relacionados",
    "treepermissions.modals.save.section3": "Nombre de la regla",
    "treepermissions.modals.save.section3.replace": "La regla ya existe, ¿quieres reemplazarla?",
    "treepermissions.modals.save.section3.required": "Es necesario un nombre de regla",
    "treepermissions.modals.save.section3.placeholder": "Escribe el nombre de la regla...",

    "treepermissions.toast.permissionsload": '¡Permisos cargados correctamente!',
    "treepermissions.toast.roleupdate": "Rol actualizado con éxito",
    "treepermissions.toast.rolecreate": "Rol creado con éxito",
    "treepermissions.toast.profileupdate": "Perfil actualizado con éxito",
    "treepermissions.toast.profilecreate": "Perfil creado con éxito",
    "treepermissions.toast.groupupdate": "Grupo actualizado con éxito",
    "treepermissions.toast.groupcreate": "Grupo creado con éxito",
    "treepermissions.toast.roledelete": "El rol '{{role}}' se eliminó correctamente",
    "treepermissions.toast.profiledelete": "El perfil '{{role}}' se eliminó correctamente",
    "treepermissions.toast.groupdelete": "El grupo '{{group}}' se eliminó correctamente",
    "treepermissions.toast.userdelete": "El usuario '{{user}}' se eliminó correctamente",
    "treepermissions.toast.deleteselerror": "Es necesario seleccionar al menos un usuario, un rol o un grupo",
    "treepermissions.toast.deleteselerrorperfil": "Es necesario seleccionar al menos un usuario, un perfil o un grupo",
    "treepermissions.toast.assignselerror01": "Es necesario seleccionar al menos un usuario y un rol o grupo",
    "treepermissions.toast.assignselerror01perfil": "Es necesario seleccionar al menos un usuario y un perfil o grupo",
    "treepermissions.toast.assignselerror02": "Solo se permite un rol por usuario",
    "treepermissions.toast.assignselerror02perfil": "Solo se permite un perfil por usuario",
    "treepermissions.toast.assignselsuccess01": "El grupo y los roles se han agregado correctamente",
    "treepermissions.toast.assignselsuccess01perfil": "El grupo y los perfiles se han agregado correctamente",
    "treepermissions.toast.assignselsuccess02": "Grupo y roles han sido reemplazados con éxito",
    "treepermissions.toast.assignselsuccess02perfil": "Grupo y perfiles han sido reemplazados con éxito",
    "treepermissions.toast.assignselsuccess03": "Rol ha sido reemplazado con éxito",
    "treepermissions.toast.assignselsuccess03perfil": "Perfil ha sido reemplazado con éxito",
    "treepermissions.toast.savedialogsuccesscreated": "Usuario creado con éxito",
    "treepermissions.toast.savedialogsuccessupdated": "Usuario actualizado con éxito",
    "treepermissions.toast.savedialogerror": "Se debe seleccionar al menos una funcionalidad",
    "treepermissions.toast.rulecreate": "La regla '{{rule}}' se creó correctamente",
    "treepermissions.toast.permissionscreate": "Permisos creados exitosamente",
    "treepermissions.toast.ruledelete": "La regla '{{rule}}' se eliminó correctamente",
    "treepermissions.toast.sequelizeerrorforeignkey": "Error, se hace referencia al registro en otra tabla",
    //Bookmark
    'views.bookmark.modolista' : `Vista modo lista`,
    'views.bookmark.mododetalle' : `Vista modo detalle`,
    'views.bookmark.mybookmark' : 'Mis marcadores',
    //EMBED
    'views.embed.mensaje' : 'Le recomendamos que incluya objetos solo en páginas web internas. La visualización se actualizará cuando se actualice la aplicación.',
    'views.embed.SI' : 'Sí',
    'views.embed.NO' : 'No',
    'views.embed.allowInteraction' : 'Permitir interacción',
    'views.embed.enableContextMenu': 'Habilitar menú contextual',
    'alerting.dial.alertas' : `Alertas`,
    'alerting.label.todas' : `Todas las alertas`,
    'alerting.label.fecha' : `Fecha/Hora`,
    'alerting.label.nombre' : `Nombre`,
    'alerting.label.mensaje' : `Mensaje`,
    'alerting.label.fechaleida' : `Fecha/Hora leída`,
    'alerting.label.leertodas' : `Marcar todas como leídas`, 
    'alerting.label.leeralerta' : `Marcar como leída`, 
    'alerting.label.noalertassinleer': `No hay alertas sin leer`,      
    'alerting.label.vertodas': `Ver todas`,
    'alerting.label.confirmacion': `Confimación`, 
    'alerting.label.confirdelete': ' ¿Eliminar la definición de alerta y su alerta?',
    'alerting.label.cancel': 'Cancelar',
    'alerting.label.configuracion': `Configuración de alerta`,
    'alerting.label.configuracion.general': `General`,
    'alerting.label.configuracion.alerta': `Alerta`,
    'alerting.label.configuracion.mensaje': `Mensaje`,
    'alerting.label.configuracion.tipo': `Tipo de alerta`,
    'alerting.label.configuracion.app': `Aplicación`,
    'alerting.label.configuracion.hoja': `Hoja de Mashup`,
    'alerting.label.configuracion.medidaCondiciones': `Medida y Condiciones`,
    'alerting.label.configuracion.medida': `Medida`,
    'alerting.label.configuracion.valores': `Valor fijo / Porcentaje`,
    'alerting.label.configuracion.tipoCondicion': `Tipo de condición`,
    'alerting.label.configuracion.maximo': `Máximo`,
    'alerting.label.configuracion.minimo': `Mínimo`,
    'alerting.label.configuracion.guardar': `Guardar`,
    'alerting.label.configuracion.eliminar': `Eliminar`,
    'alerting.label.configuracion.cerrar': `Cerrar`,
    'alerting.label.configuracion.master.error': `Error`,
    'alerting.label.configuracion.master.advertencia': `Advertencia`,
    'alerting.label.configuracion.master.informacion': `Información`,
    'alerting.label.configuracion.master.exito': `Éxito`,
    'alerting.label.configuracion.master.data': `Sobre los datos`,
    'alerting.label.configuracion.master.system': `De sistema`,
    'alerting.label.configuracion.master.valorFijo': `Valor fijo`,
    'alerting.label.configuracion.master.valorPorcentaje': `Porcentaje`,
    'alerting.label.configuracion.master.minmax': `Mínimo-Máximo`,
    'alerting.label.configuracion.master.min': `Mínimo`,
    'alerting.label.configuracion.master.max': `Máximo`,
    'alerting.toast.mensajeCreacionAlerta' : `Se ha creado la alerta`,
    'alerting.toast.mensajeEliminacionAlerta' : `Se ha eliminado la definición y su alerta`,
    'alerting.toast.mensajeCreacionDefinicion' : `Se ha creado la definición de alerta`,
    'alerting.toast.mensajeEliminacionDefinicion' : `Se ha eliminado la definición`,
    'alerting.toast.mensajeActualizacionDefinicion' : `Se ha actualizado la definición de alerta`,
    'grid.header.tituloGrafico' : `Título gráfico`,
    'grid.header.tipoGrafico' : `Tipo gráfico`,
    'grid.header.seccionGrafico' : `Sección`,
    'grid.header.idGrafico' : `ID gráfico`,
    'grid.header.fechaCreación' : `Añadido`,
    'grid.header.rutaLocalizacion' : `Ruta localización`,
    'grid.header.acciones' : `Acciones`,
    'grid.header.fecha-creacion' : `Fecha de creación`,
    'grid.header.fecha-modificacion' : `Fecha de modificación`,
    'grid.header.tipo-grafico' : `Tipo gráfico`,
    'grid.header.user' : `Usuario`,
    'grid.header.seccion' : `Sección`,
    //AYUDA OBJETOS
    'help.label.descripcionTab' : 'Descripción',
    'help.label.detalleTab' : 'Detalle',
    'help.label.layoutTab' : 'Layout',
    'help.btn.editar' : 'Editar',
    'help.txt.detalleTab' : '<h2>Dimensiones:</h2><p>Las dimensiones son atributos que organizan y categorizan los datos. Representan las variables que se utilizan para dividir, agrupar o segmentar los datos en una aplicación de Qlik Sense.</p><p>Las dimensiones permiten realizar análisis detallados y desglosar los datos en diferentes categorías.</p><p>En visualizaciones como tablas y gráficos, las dimensiones se colocan en ejes, filas o columnas para organizar la información.</p><p>Al seleccionar o interactuar con una dimensión, se recalculan dinámicamente las medidas asociadas, permitiendo una exploración interactiva de los datos.</p><h2>Medidas:</h2><p>Las medidas representan los valores numéricos que se analizan y agregan en una aplicación de Qlik Sense. Son las métricas cuantitativas que proporcionan información sobre el rendimiento, las ventas, las cantidades, etc.</p><p>Las medidas son utilizadas para realizar cálculos y agregaciones sobre los datos de las dimensiones.</p><p>En gráficos y tablas, las medidas se utilizan en ejes Y o como valores para representar la magnitud de los datos.</p><p>Las medidas son esenciales para entender la magnitud y la tendencia de los datos, permitiendo realizar análisis comparativos y obtener insights cuantitativos.</p><h2>Relación entre Dimensiones y Medidas:</h2><p>Las dimensiones y medidas trabajan juntas para proporcionar una comprensión completa de los datos. Las dimensiones organizan y agrupan los datos, mientras que las medidas realizan cálculos sobre esos datos agrupados.</p><p>Al realizar selecciones en las dimensiones, las medidas se ajustan automáticamente para reflejar el impacto de esas selecciones, permitiendo una exploración interactiva y dinámica de los datos.</p>',
    'help.txt.selectIdioma' : 'Selecciona un idioma para guardar los cambios',
    //PRESENTACIÓN
    'presentacion.tooltips.init' : 'Modo presentación'

};
var custom = {
    'view.wellcome.bigText': `Explora tus datos sin límites.`,
    'view.wellcome.smallText': `Potencia el talento de tu equipo, transformando datos en decisiones estratégicas.`,  
    'view.menu.ventas': 'Ventas',
    "view.menu.compras": "Compras",
    'view.menu.financiero': 'Financiero',
    'view.menu.logistica':'Logística',
    'view.menu.personal' : 'Personal',
    'view.menu.crm':'CRM',
    'view.menu.produccion' : 'Producción',
    'view.menu.nps' : 'NPS',
    'view.wellcomeMenu.favoritos': `Favoritos`,
    'label.filtro.calendario': 'Calendario',
    'label.filtro.anios': 'Años'
}
var translationsES = $.extend(true, appES, custom);